ARCH-1919 - Transfer to Infra-Purple
- Update CODEOWNERS
- Add tests to build-and-review-pr.yml

diff --git a/.github/workflows/build-and-review-pr.yml b/.github/workflows/build-and-review-pr.yml
--- a/.github/workflows/build-and-review-pr.yml
+++ b/.github/workflows/build-and-review-pr.yml
@@ -60,3 +60,86 @@ jobs:
       # The npm script to run to build the action.  This is typically 'npm run build' if the
       # action needs to be compiled.  For composite-run-steps actions this is typically empty.
       build-command: 'npm run build'
+
+  test-action:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-node@v2
+        with:
+          node-version: '14'
+
+      #------------------------------------------
+      # ACTOR IS NOT IN LIST OF AUTHORIZED ACTORS
+      #------------------------------------------
+      - name: Use action with an actor that is not in list of authorized actors
+        if: always()
+        id: failure
+        uses: ./
+        with:
+          actor: 'pikachu12'
+          authorized-actors: |
+            [
+              "pika1",
+              "pika2",
+              "pika3"
+            ]
+
+      - name: Validate 'actor not in list' step outcome
+        if: always()
+        run: |
+          if [ "${{ steps.failure.outcome }}" != "failure" ]; then
+            echo "Expected 'failure' but got '${{ steps.failure.outcome }}'"
+            exit 1
+          else
+            echo "The step outcome was 'failure' as expected"
+          fi
+
+      #--------------------------------------
+      # ACTOR IS IN LIST OF AUTHORIZED ACTORS
+      #--------------------------------------
+      - name: Use action with an actor in the list of authorized actors
+        if: always()
+        id: success
+        uses: ./
+        with:
+          actor: 'pikachu12'
+          authorized-actors: |
+            [
+              "pika1",
+              "pika2",
+              "pika3",
+              "pikachu12"
+            ]
+
+      - name: Validate 'actor in list' step outcome
+        if: always()
+        run: |
+          if [ "${{ steps.success.outcome }}" != "success" ]; then
+            echo "Expected 'success' but got '${{ steps.success.outcome }}'"
+            exit 1
+          else
+            echo "The step outcome was 'success' as expected"
+          fi
+
+      #--------------------------------------
+      # AUTHORIZED ACTORS LIST IS EMPTY
+      #--------------------------------------
+      - name: Use action with an empty authorized actors list
+        if: always()
+        id: empty
+        uses: ./
+        with:
+          actor: 'pikachu12'
+          authorized-actors: '[]'
+      
+      - name: Validate 'empty authorized actors list' step outcome
+        if: always()
+        run: |
+          if [ "${{ steps.failure.outcome }}" != "failure" ]; then
+            echo "Expected 'failure' but got '${{ steps.failure.outcome }}'"
+            exit 1
+          else
+            echo "The step outcome was 'failure' as expected"
+          fi
